<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240425164436" tests="4" file="unittest/loader.py" time="0.005" timestamp="2024-04-25T16:44:36" failures="0" errors="4" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test_singleton_hotel_manager_tests" time="0.002" timestamp="2024-04-25T16:44:36">
		<error type="ImportError" message="Failed to import test module: test_singleton_hotel_manager_tests
Traceback (most recent call last):
  File &quot;/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_singleton_hotel_manager_tests.py&quot;, line 3, in &lt;module&gt;
    from uc3m_travel import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 18, in &lt;module&gt;
    from uc3m_travel.storage.json_store import write_json
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py&quot;, line 3, in &lt;module&gt;
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 34, in testFailure
    raise self._exception
    ^^^^^^^^^^^^^^^^^
ImportError: Failed to import test module: test_singleton_hotel_manager_tests
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_singleton_hotel_manager_tests.py", line 3, in <module>
    from uc3m_travel import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py", line 18, in <module>
    from uc3m_travel.storage.json_store import write_json
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py", line 3, in <module>
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_checkout_tests" time="0.001" timestamp="2024-04-25T16:44:36">
		<error type="ImportError" message="Failed to import test module: test_checkout_tests
Traceback (most recent call last):
  File &quot;/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_checkout_tests.py&quot;, line 7, in &lt;module&gt;
    from uc3m_travel import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 18, in &lt;module&gt;
    from uc3m_travel.storage.json_store import write_json
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py&quot;, line 3, in &lt;module&gt;
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 34, in testFailure
    raise self._exception
    ^^^^^^^^^^^^^^^^^
ImportError: Failed to import test module: test_checkout_tests
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_checkout_tests.py", line 7, in <module>
    from uc3m_travel import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py", line 18, in <module>
    from uc3m_travel.storage.json_store import write_json
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py", line 3, in <module>
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_guest_arrival_tests" time="0.001" timestamp="2024-04-25T16:44:36">
		<error type="ImportError" message="Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File &quot;/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_guest_arrival_tests.py&quot;, line 10, in &lt;module&gt;
    from uc3m_travel import (JSON_FILES_PATH,
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 18, in &lt;module&gt;
    from uc3m_travel.storage.json_store import write_json
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py&quot;, line 3, in &lt;module&gt;
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 34, in testFailure
    raise self._exception
    ^^^^^^^^^^^^^^^^^
ImportError: Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_guest_arrival_tests.py", line 10, in <module>
    from uc3m_travel import (JSON_FILES_PATH,
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py", line 18, in <module>
    from uc3m_travel.storage.json_store import write_json
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py", line 3, in <module>
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_room_reservation_tests" time="0.001" timestamp="2024-04-25T16:44:36">
		<error type="ImportError" message="Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File &quot;/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_room_reservation_tests.py&quot;, line 9, in &lt;module&gt;
    from uc3m_travel import (JSON_FILES_PATH,
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py&quot;, line 3, in &lt;module&gt;
    from .hotel_manager import HotelManager
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py&quot;, line 18, in &lt;module&gt;
    from uc3m_travel.storage.json_store import write_json
  File &quot;/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py&quot;, line 3, in &lt;module&gt;
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)
"><![CDATA[Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 34, in testFailure
    raise self._exception
    ^^^^^^^^^^^^^^^^^
ImportError: Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/unittest/python/test_room_reservation_tests.py", line 9, in <module>
    from uc3m_travel import (JSON_FILES_PATH,
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py", line 3, in <module>
    from .hotel_manager import HotelManager
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/hotel_manager.py", line 18, in <module>
    from uc3m_travel.storage.json_store import write_json
  File "/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/storage/json_store.py", line 3, in <module>
    from uc3m_travel import HotelManagementException
ImportError: cannot import name 'HotelManagementException' from partially initialized module 'uc3m_travel' (most likely due to a circular import) (/Users/tito/Library/CloudStorage/GoogleDrive-100495775@alumnos.uc3m.es/My Drive/2.UC3M/2.Classes/SoftwareDev/Lab/G88.2024.T12.GE3/src/main/python/uc3m_travel/__init__.py)

]]></error>
	</testcase>
</testsuite>
